FROM alpine:3


LABEL author="Herliana Nur Ekawati"
LABEL company="Institut Teknologi Kalimantan" website="https://itk.ac.id"

RUN mkdir praktikum
RUN echo "Tugas Sister Dockerfile" > "praktikum/tugas.txt"

CMD cat "praktikum/tugas.txt"